namespace MtgTtsBridge.Contracts.Events;

public sealed record AuthoritativeEventDto(
    long Sequence,
    string EventId,
    string Kind,
    string? SeatId,
    string? CardName,
    int? ForgeObjectId,
    string? CardInstanceId,
    string? SourceZone,
    string? DestinationZone,
    string Summary,
    DateTimeOffset OccurredAtUtc,
    int? LifeTotal = null,
    int? PoisonCounters = null,
    string? CounterType = null,
    int? CounterValue = null,
    string? Keyword = null,
    bool? Tapped = null,
    bool ContainsHiddenIdentity = false,
    IReadOnlyDictionary<string, int>? ManaPool = null,
    string? Phase = null,
    int? TurnNumber = null,
    long? ForgeSequence = null,
    string? ActiveSeatId = null,
    string? PrioritySeatId = null,
    int? NetPower = null,
    int? NetToughness = null,
    int? CurrentPower = null,
    int? CurrentToughness = null,
    IReadOnlyList<string>? CurrentTypes = null,
    string? CurrentCardName = null,
    string? OwnerSeatId = null,
    string? ControllerSeatId = null,
    bool? FaceDown = null,
    bool? PhasedOut = null,
    int? Speed = null,
    IReadOnlyList<string>? Designations = null,
    string? MonarchSeatId = null,
    IReadOnlyList<string>? WinnerSeatIds = null,
    IReadOnlyList<string>? LoserSeatIds = null,
    string? GameEndReason = null);

public sealed record EventBatchDto(
    long RequestedAfterSequence,
    long OldestAvailableSequence,
    long LatestSequence,
    bool HasGap,
    IReadOnlyList<AuthoritativeEventDto> Events);
